connections {
  pqc-hybrid {
    version = 2
    proposals = aes256gcm128-prfsha384-x25519-mlkem768
    local_addrs = 0.0.0.0
    remote_addrs = %any
    fragmentation = yes
    local {
      auth = pubkey
      certs = server_mldsa65.crt
      id = pqc-vpn.local
    }
    remote {
      auth = pubkey
      id = %any
    }
    children {
      net {
        local_ts = 10.10.0.0/24
        remote_ts = 10.20.0.0/24
        esp_proposals = aes256gcm128-sha384
      }
    }
  }
}
